services:
    project:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
    main-postgres:
        user: ${USER_ID:-1000}:${GROUP_ID:-1000}
        container_name: main-postgres
        image: postgres:15.2-alpine
        environment:
            POSTGRES_DB: main
            POSTGRES_PASSWORD: password
            POSTGRES_USER: app
        ports:
            - "5434:5432"
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
